[buttons_ru]
yes = '‚úÖ –î–∞'
no = '‚ùå –ù–µ—Ç'
exit = '‚ùå –í—ã—Ö–æ–¥'
profile = "üîë –ú–æ–π –ø—Ä–æ—Ñ–∏–ª—å"
metodic = "üìí –ú–µ—Ç–æ–¥–∏—á–∫–∏"
textbook = "üìñ –£—á–µ–±–Ω–∏–∫"
shedule = "üìÜ –†–∞—Å–ø–∏—Å–∞–Ω–∏–µ –ø—Ä–µ–ø–æ–¥–∞–≤–∞—Ç–µ–ª—è"
graph_task = '‚úÖ –°–¥–∞—Ç—å –∑–∞–¥–∞—á—É'
contact = "üìû –ö–æ–Ω—Ç–∞–∫—Ç—ã –ø—Ä–µ–ø–æ–¥–∞–≤–∞—Ç–µ–ª—è"
today = '–°–µ–≥–æ–¥–Ω—è'
tomorrow = '–ó–∞–≤—Ç—Ä–∞'
after_tom = '–ü–æ—Å–ª–µ–∑–∞–≤—Ç—Ä–∞'
to_2_day = '–ß–µ—Ä–µ–∑ 2 –¥–Ω—è'
all = '–í—Å–µ'
mailer = '‚úÖ –†–∞—Å—Å—ã–ª–∫–∞'
question = '‚ùì –í–æ–ø—Ä–æ—Å –ø—Ä–µ–ø–æ–¥–∞–≤–∞—Ç–µ–ª—é'
send = '–û—Ç–≤–µ—Ç–∏—Ç—å'

[user]
exit_reg = '–í—ã –≤—ã—à–ª–∏ –∏–∑ –º–µ–Ω—é —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏–∏.'
available = "–ü–æ–¥—Ç–≤–µ—Ä–¥–∏—Ç–µ –ª–∏—á–Ω–æ—Å—Ç—å: {name}, –Ω–∞–ø—Ä–∞–≤–ª–µ–Ω–∏–µ {profile}, –≥—Ä—É–ø–ø–∞ {group}"
uncorrect = "–ù–µ–ø—Ä–∞–≤–∏–ª—å–Ω–æ, –ø–æ–ø—Ä–æ–±—É–π –µ—â—ë —Ä–∞–∑!"
yes = "–ü—Ä–∏—è—Ç–Ω–æ –ø–æ–∑–Ω–∞–∫–æ–º–∏—Ç—å—Å—è! –Ø –∑–∞—Ä–µ–≥–∏—Å—Ç—Ä–∏—Ä–æ–≤–∞–ª –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è: {name}, –ø—Ä–æ—Ñ–∏–ª—å {profile}, –≥—Ä—É–ø–ø–∞ {group}. –¢–µ–ø–µ—Ä—å —Ç—ã –º–æ–∂–µ—à—å –ø–æ–ª—å–∑–æ–≤–∞—Ç—å—Å—è –ø—Ä–æ–¥–≤–∏–Ω—É—Ç—ã–º —Ä–µ–∂–∏–º–æ–º —á–∞—Ç-–±–æ—Ç–∞."
no = "–•–æ—Ä–æ—à–æ, –ø–æ–ø—Ä–æ–±—É–π—Ç–µ —Å–Ω–æ–≤–∞."
register_admin = "–ó–∞—Ä–µ–≥–∏—Å—Ç—Ä–∏—Ä–æ–≤–∞–Ω –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å {name}, –ø—Ä–æ—Ñ–∏–ª—å {profile}, –≥—Ä—É–ø–ø–∞ {group}."
question = "–ó–∞–¥–∞–π—Ç–µ —Å–≤–æ–π –≤–æ–ø—Ä–æ—Å –ø—Ä–µ–ø–æ–¥–∞–≤–∞—Ç–µ–ª—é!"
get_question = "–°–ø–∞—Å–∏–±–æ, –≤–æ–ø—Ä–æ—Å –æ—Ç–ø—Ä–∞–≤–ª–µ–Ω –ø—Ä–µ–ø–æ–¥–∞–≤–∞—Ç–µ–ª—é!"
send_question = "## –í–æ–ø—Ä–æ—Å {user_id}\n–û–±—É—á–∞—é—â–∏–π—Å—è {name}, {profile}-{group}"
graph_task = "–í—ã–±–µ—Ä–∏—Ç–µ –∑–∞–¥–∞—á—É, –∫–æ—Ç–æ—Ä—É—é —Ö–æ—Ç–∏—Ç–µ —Å–¥–∞—Ç—å."
graph_task_prepod = "–ó–∞–ø—Ä–æ—Å –Ω–∞ –æ—Ü–µ–Ω–∫—É –∑–∞–¥–∞—á–∏ {task} –æ–±—É—á–∞—é—â–µ–º—É—Å—è {name}."
graph_task_call = "–ó–∞—è–≤–∫–∞ –Ω–∞ –ø—Ä–∏—ë–º –∑–∞–¥–∞—á–∏ {task} –æ—Ç–ø—Ä–∞–≤–ª–µ–Ω–∞ –ø—Ä–µ–ø–æ–¥–∞–≤–∞—Ç–µ–ª—é."
graph_task_score_prepod = "–û–±—É—á–∞—é—â–µ–º—É—Å—è {name} –≤—ã—Å—Ç–∞–≤–ª–µ–Ω –±–∞–ª–ª \"{score}\" –∑–∞ –∑–∞–¥–∞—á—É {task}."
graph_task_score_user = "–ü–æ–∑–¥—Ä–∞–≤–ª—è—é! –ó–∞ –∑–∞–¥–∞—á—É {task} —Ç–µ–±–µ –≤—ã—Å—Ç–∞–≤–ª–µ–Ω –±–∞–ª–ª \"{score}\"."

[admin]
mailer_cancel = "–†–∞—Å—Å—ã–ª–∫–∞ –æ—Ç–º–µ–Ω–µ–Ω–∞ –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–æ—Ä–æ–º."
reply_question = "–ù–∞–ø–∏—à–∏—Ç–µ –æ—Ç–≤–µ—Ç –Ω–∞ –≤–æ–ø—Ä–æ—Å."
send_question = "–ü–æ–ª—É—á–µ–Ω –æ—Ç–≤–µ—Ç –æ—Ç –ø—Ä–µ–ø–æ–¥–∞–≤–∞—Ç–µ–ª—è."
available_reply = "–ü–æ–¥—Ç–≤–µ—Ä–¥–∏—Ç–µ –æ—Ç–ø—Ä–∞–≤–∫—É –æ—Ç–≤–µ—Ç–∞."
question_succesful = "–û—Ç–≤–µ—Ç –æ—Ç–ø—Ä–∞–≤–ª–µ–Ω –¥–ª—è {user_id}."

[commands]
start = "–ü—Ä–∏–≤–µ—Ç—Å—Ç–≤—É—é, {name}! –Ø —Ç–≤–æ–π –ø–æ–º–æ—â–Ω–∏–∫ –≤ –æ–±–ª–∞—Å—Ç–∏ —Ç–µ–æ—Ä–µ—Ç–∏—á–µ—Å–∫–æ–π –º–µ—Ö–∞–Ω–∏–∫–∏. \n–ï—Å–ª–∏ —Ç—ã —Ö–æ—á–µ—à—å –∑–∞—Ä–µ–≥–∏—Å—Ç—Ä–∏—Ä–æ–≤–∞—Ç—å—Å—è –∫–∞–∫ –æ–±—É—á–∞—é—â–∏–π—Å—è —Å –ø—Ä–∞–≤–∞–º–∏ –¥–æ—Å—Ç—É–ø–∞, —Ç–æ –≤—ã–ø–æ–ª–Ω–∏ –∫–æ–º–∞–Ω–¥—É /register. \n–î–ª—è –æ—Ç–∫—Ä—ã—Ç–∏—è —Å–ø—Ä–∞–≤–∫–∏ –≤—ã–ø–æ–ª–Ω–∏ –∫–æ–º–∞–Ω–¥—É /help."
help = "–ü—Ä–∏–≤–µ—Ç! –Ø —Ç–≤–æ–π —Ä–æ–±–æ—Ç-–ø–æ–º–æ—â–Ω–∏–∫ –≤ –æ—Å–≤–æ–µ–Ω–∏–∏ –ø—Ä–µ–¥–º–µ—Ç–∞ '–¢–µ–æ—Ä–µ—Ç–∏—á–µ—Å–∫–∞—è –º–µ—Ö–∞–Ω–∏–∫–∞'. \n–í –º–µ–Ω—é –≤—Å—Ç—Ä–æ–µ–Ω–Ω–æ–π –∫–ª–∞–≤–∏–∞—Ç—É—Ä—ã —Ç—ã –º–æ–∂–µ—à—å –Ω–∞–π—Ç–∏ –ø–æ—Å–æ–±–∏—è –¥–ª—è —Å–∞–º–æ—Å—Ç–æ—è—Ç–µ–ª—å–Ω–æ–π —Ä–∞–±–æ—Ç—ã, —É—á–µ–±–Ω–∏–∫.\n–¢–∞–∫–∂–µ –≤–æ–∑–º–æ–∂–Ω–æ –Ω–∞–π—Ç–∏ –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –≤ —Å–≤–æ—ë–º –ø—Ä–æ—Ñ–∏–ª–µ, —Ä–∞—Å–ø–∏—Å–∞–Ω–∏–µ –ø—Ä–µ–ø–æ–¥–∞–≤–∞—Ç–µ–ª—è, —Å–¥–∞—Ç—å –∑–∞–¥–∞—á—É –∏ —Ä–µ—à–∞—Ç—å —Å–µ–º–∏–Ω–∞—Ä—Å–∫–∏–µ –∑–∞–¥–∞—á–∏.\n–°–ø–∏—Å–æ–∫ –¥–æ—Å—Ç—É–ø–Ω—ã—Ö –∫–æ–º–∞–Ω–¥:\n  /help - –≤—ã–≤–µ—Å—Ç–∏ —Å–ø—Ä–∞–≤–∫—É –ø–æ —á–∞—Ç-–±–æ—Ç—É\n  /menu - –≤—ã–∑–æ–≤ –≤—Å—Ç—Ä–æ–µ–Ω–Ω–æ–π –∫–ª–∞–≤–∏–∞—Ç—É—Ä—ã\n  /cancel - –æ—Ç–º–µ–Ω–∞ —Å–æ—Å—Ç–æ—è–Ω–∏—è —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏–∏.\nP.S. –ï—Å–ª–∏ —è –¥–æ–ª–≥–æ –æ—Ç–≤–µ—á–∞—é, –ø—Ä–æ—Å—Ç–∏ üòá\n\n–†–∞–∑—Ä–∞–±–æ—Ç—á–∏–∫ ¬© –Æ—Ä–∏–π –°–æ–ª–¥–∞—Ç–æ–≤"
register = "–î–∞–≤–∞–π –ø–æ–∑–Ω–∞–∫–æ–º–∏–º—Å—è, –Ω–∞–ø–∏—à–∏ —Å–≤–æ—é —Ñ–∞–º–∏–ª–∏—é –∏–º—è –æ—Ç—á–µ—Å—Ç–≤–æ. –ï—Å–ª–∏ —Ç—ã —Ö–æ—á–µ—à—å –≤—ã–π—Ç–∏ –∏–∑ –ø—Ä–æ—Ü–µ—Å—Å–∞ —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏–∏, –Ω–∞–∂–º–∏ '–í—ã—Ö–æ–¥'"
cancel = "–í—ã –≤—ã—à–ª–∏ –∏–∑ –º–µ–Ω—é —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏–∏."
cancel_not = "–û—Ç–º–µ–Ω—è—Ç—å –Ω–µ—á–µ–≥–æ, –≤—ã –≤–Ω–µ –º–µ–Ω—é –¥–∏–∞–ª–æ–≥–∞. \n–î–ª—è —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏–∏ –≤—ã–ø–æ–ª–Ω–∏—Ç–µ –∫–æ–º–∞–Ω–¥—É /register"
menu = "–ö–ª–∞–≤–∏–∞—Ç—É—Ä–∞ –≤—ã–≤–µ–¥–µ–Ω–∞ ‚å®Ô∏è"
admin = "–í—ã –≤–æ—à–ª–∏ –≤ –º–µ–Ω—é –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–æ—Ä–∞"
